version: 2.1
jobs:
  # ビルドジョブ
  deploy-dev:
    working_directory: ~/app
    docker:
      - image: circleci/node:12.16.3
    steps:
      # チェックアウトとは、リポジトリからファイルを取得すること。
      - checkout
      # 依存関係のキャッシュ
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package-lock.json" }}
            - npm-dependencies-
      # name、commandの先頭にインデントをいれていなかったためエラーに引っかかった
      - run:
          name: Install Dependency
          command: npm install
      # ビルド実行
      - run:
          name: Build
          command: npm run build
      # キャッシュを保存
      - save_cache:
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/app/node_modules
            - ~/app/dist
          force: yes
      - run:
          name: deploy
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
        # command: ./node_modules/.bin/firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"
  # デプロイジョブ
  # deploy:
  #   working_directory: ~/app
  #   docker:
  #     - image: circleci/node:12.16.3
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
  #           - npm-{{ .Branch }}-
  #           - npm-
  #     - run:
  #         name: Install Dependency
  #         command: npm install
  #     - run:
  #         name: deploy
  #         command: ./node_modules/.bin/firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"
workflows:
  version: 2.1
  build_deploy:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only: master